/**
 * Skills packaging (roster DESIGN §7, IMPLEMENTATION M5).
 *
 * §7.1's decision in one line: **the agent folder is a local plugin**, because
 * that is the only supported route for skills that live with the *agent* rather
 * than with the host machine (`~/.claude/skills/`) or the target project
 * (`<cwd>/.claude/skills/`). `.claude-plugin/plugin.json` is generated by the
 * store (§7.1, M2); this module owns everything downstream of it: what is on
 * disk, what the SDK is asked to enable, and whether the session it started
 * agrees.
 *
 * Four facts shape the code, three of them from SDK-NOTES:
 *
 * - **Omitting `skills` is not "off".** `sdk.d.ts:1995`: "the CLI's own defaults
 *   still apply". So the key is emitted on every launch, `[]` included — M4
 *   already does this and {@link skillsEnableSet} keeps it true.
 * - **Names must be exact.** "No wildcards, no padding — or the SDK throws
 *   before the process starts" (§7.2). A throw at `query()` is not a failure
 *   this element may hand to the runner, so names are validated against the
 *   folder listing at write time (a refusal) and again at launch (a diagnostic
 *   plus the name dropped, so the session still starts).
 * - **A nonexistent plugin path is silently skipped, and `~` is not expanded**
 *   (§7.1). Hence absolute paths only, and hence {@link assertSessionStart} —
 *   the only way to find out that a plugin did not load is to read the init
 *   message and compare.
 * - **`skipMcpDiscovery` exists** (SDK-NOTES §4) and is taken. Roster owns MCP
 *   wiring through `integrations` (§10); with it set, an agent folder that
 *   acquires a stray `.mcp.json` — by hand-edit, or by a `git pull` of a shared
 *   library — cannot mount a server the compiler never approved.
 */
import { readdirSync } from 'node:fs';
import { isAbsolute, join } from 'node:path';

import type { Diagnostic } from './contracts.js';
import type { AgentDefinition, Skills } from './schema.js';

/**
 * Per-agent skills, in plugin layout (§2.1, §7).
 *
 * Declared here rather than beside the rest of the layout constants in
 * `store.ts` because the store *imports this module* to validate a folder as it
 * loads it, and a constant defined on the far side of that import would be a
 * cycle. `store.ts` re-exports it, so the layout section still reads as one
 * list.
 */
export const SKILLS_DIRNAME = 'skills';

/**
 * The tool §7.2 adds to the effective allow set.
 *
 * Setting the `skills` option auto-adds the tool, and SDK-NOTES §5 records that
 * "you do not need to add `'Skill'` to `allowedTools` yourself" — so this entry
 * is about *auto-approval*, not availability: without it every skill invocation
 * would reach the permission gate and prompt.
 */
export const SKILL_TOOL = 'Skill';

// ---------------------------------------------------------------------------
// What is on disk
// ---------------------------------------------------------------------------

/**
 * The skill folder names directly under `<agentDir>/skills/`.
 *
 * Directories only, dot-folders excluded, sorted — the same shape the store's
 * folder listing uses, and the same exclusions, so a `.git` or an in-flight
 * temp directory is never mistaken for a skill.
 */
export function listSkillNames(agentDir: string): string[] {
  let entries;
  try {
    entries = readdirSync(join(agentDir, SKILLS_DIRNAME), { withFileTypes: true });
  } catch {
    // No `skills/` is an agent with no skills, not a failure.
    return [];
  }
  return entries
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith('.'))
    .map((entry) => entry.name)
    .sort();
}

// ---------------------------------------------------------------------------
// Validation (§7.2, "at write time and again at launch")
// ---------------------------------------------------------------------------

/** Declared names with no folder to back them. Empty for `all` and `none`. */
export function missingSkillFolders(
  skills: Skills | undefined,
  available: readonly string[],
): string[] {
  if (skills?.mode !== 'declared') return [];
  const present = new Set(available);
  return (skills.names ?? []).filter((name) => !present.has(name));
}

/**
 * The write-time check.
 *
 * `error` level, because M5's acceptance is that a declared name with no folder
 * is "rejected at write time with a message naming the missing folder — not at
 * launch". The service turns this into a refusal; the store turns the same call
 * into a diagnostic on a folder that arrived by hand-edit or `git pull`, where
 * refusing is not an option because there is nobody to refuse.
 */
export function validateSkills(
  definition: Pick<AgentDefinition, 'id' | 'skills'>,
  available: readonly string[],
  agentDir?: string,
): Diagnostic[] {
  const missing = missingSkillFolders(definition.skills, available);
  if (missing.length === 0) return [];
  const where = agentDir === undefined ? SKILLS_DIRNAME : join(agentDir, SKILLS_DIRNAME);
  return missing.map((name) => ({
    level: 'error' as const,
    code: 'roster.skills.missing-folder',
    message:
      `skills.names lists "${name}", but there is no folder ${join(where, name)}. ` +
      'Skill names must be exact folder names — the SDK throws before the session starts ' +
      'if it is asked to enable one it cannot find (DESIGN §7.2).',
    agentId: definition.id,
    path: `skills.names`,
  }));
}

// ---------------------------------------------------------------------------
// The `skills` option (§7.2)
// ---------------------------------------------------------------------------

export interface SkillsEnableSet {
  /** The value of `options.skills`. Always present — omitting the key is not
   *  "off" (SDK-NOTES §5). */
  readonly skills: string[] | 'all';
  /** Whether anything can fire: the condition for mounting the plugin and for
   *  adding {@link SKILL_TOOL} to the allow set. */
  readonly enabled: boolean;
  readonly diagnostics: readonly Diagnostic[];
}

/**
 * §7.2's mapping — `declared` → the exact names, `all` → `'all'`, `none` (and an
 * agent with no `skills` block at all) → `[]` — with the launch-time half of the
 * exactness check applied.
 *
 * A declared name whose folder has gone (deleted externally, or lost in a
 * partial `git pull`) is **dropped with a diagnostic** rather than passed
 * through: passing it through is the one behaviour that fails the whole launch,
 * and M5's acceptance is explicit that this case "produces a diagnostic on
 * reload rather than a broken launch".
 *
 * `available` is `undefined` when the caller does not know the folder listing —
 * a compile against an agent that was never read from disk. Then the names are
 * taken on trust, because inventing a failure from ignorance would be worse.
 */
export function skillsEnableSet(
  definition: Pick<AgentDefinition, 'id' | 'skills'>,
  available: readonly string[] | undefined,
): SkillsEnableSet {
  const skills = definition.skills;
  if (skills === undefined || skills.mode === 'none') {
    return { skills: [], enabled: false, diagnostics: [] };
  }
  if (skills.mode === 'all') {
    return { skills: 'all', enabled: true, diagnostics: [] };
  }

  const declared = [...(skills.names ?? [])];
  if (available === undefined) {
    return { skills: declared, enabled: declared.length > 0, diagnostics: [] };
  }

  const present = new Set(available);
  const kept = declared.filter((name) => present.has(name));
  const missing = declared.filter((name) => !present.has(name));

  const diagnostics: Diagnostic[] = missing.map((name) => ({
    level: 'warn' as const,
    code: 'roster.skills.missing-folder',
    message:
      `skill "${name}" is declared but has no folder under ${SKILLS_DIRNAME}/; it was dropped ` +
      'from this launch so the session can still start (DESIGN §7.2). Fix the definition or ' +
      'restore the folder.',
    agentId: definition.id,
    path: 'skills.names',
  }));

  return { skills: kept, enabled: kept.length > 0, diagnostics };
}

// ---------------------------------------------------------------------------
// The plugin config (§7.1)
// ---------------------------------------------------------------------------

/**
 * `SdkPluginConfig`, restated structurally.
 *
 * This module deliberately does not import the SDK: §13 keeps SDK option shapes
 * in `sessionOptions.ts` and `compileSession.ts`, and this object is assignable
 * to `SdkPluginConfig` by structure, so the pin still fails the typecheck if the
 * declaration moves.
 */
export interface AgentPluginConfig {
  readonly type: 'local';
  /** Absolute. `~` is not expanded and a nonexistent path is silently skipped. */
  readonly path: string;
  /**
   * Always `true`. "The engine loads skills/hooks/agents/commands from this
   * plugin but does NOT read its `.mcp.json` or manifest `mcpServers`"
   * (SDK-NOTES §4). Roster approves every MCP server through §10, and a folder
   * that acquired a stray `.mcp.json` must not be able to mount one behind the
   * compiler's back.
   */
  readonly skipMcpDiscovery: true;
}

/**
 * Absolute-path check that holds on both platforms.
 *
 * `node:path`'s `isAbsolute` is platform-specific: a Windows library root
 * (`C:\library\agents\priya`) is *not* absolute to a POSIX build of Node, and
 * the compiler's tests must not pass or fail on which machine ran them. A path
 * that either `node:path` or the Windows drive-letter form calls absolute is
 * absolute for this purpose.
 */
export function isAbsoluteAgentDir(path: string): boolean {
  return isAbsolute(path) || /^[A-Za-z]:[\\/]/.test(path);
}

/** The `plugins` entry for an agent folder, or `undefined` with a diagnostic
 *  when the path is one the SDK would silently skip. */
export function pluginConfigFor(
  agentId: string,
  agentDir: string | undefined,
): { readonly plugin: AgentPluginConfig | undefined; readonly diagnostics: readonly Diagnostic[] } {
  if (agentDir === undefined) {
    return {
      plugin: undefined,
      diagnostics: [
        {
          level: 'warn',
          code: 'roster.skills.no-agent-directory',
          message:
            'this agent has skills enabled but the compiler was not told where its folder is, ' +
            'so no plugin could be mounted and no skill will load (DESIGN §7.1)',
          agentId,
          path: 'skills',
        },
      ],
    };
  }
  if (!isAbsoluteAgentDir(agentDir)) {
    return {
      plugin: undefined,
      diagnostics: [
        {
          level: 'warn',
          code: 'roster.skills.relative-plugin-path',
          message:
            `the agent folder "${agentDir}" is not an absolute path; the SDK does not expand "~" ` +
            'and silently skips a plugin path it cannot resolve, so no skill would load ' +
            '(DESIGN §7.1)',
          agentId,
          path: 'skills',
        },
      ],
    };
  }
  return {
    plugin: { type: 'local', path: agentDir, skipMcpDiscovery: true },
    diagnostics: [],
  };
}
